$(document).ready(function(){
    $(".clickable1").click(function(){
        $(".img11").toggle();
        $(".textclickable1").toggle();
    });
    $(".clickable2").click(function(){
        $(".img22").toggle();
        $(".textclickable2").toggle();
    });
    $(".clickable3").click(function(){
        $(".img33").toggle();
        $(".textclickable3").toggle();
    });
    $(".clickable4").click(function(){
        $(".img44").toggle();
        $(".textclickable4").toggle();
    });
    $(".clickable5").click(function(){
        $(".img55").toggle();
        $(".textclickable5").toggle();
    });
    $(".clickable6").click(function(){
        $(".img66").toggle();
        $(".textclickable6").toggle();
    });
    $(".clickable7").click(function(){
        $(".img77").toggle();
        $(".textclickable7").toggle();
    });
    $(".clickable8").click(function(){
        $(".img88").toggle();
        $(".textclickable8").toggle();
    });
    $(".clickable9").click(function(){
        $(".img99").toggle();
        $(".textclickable9").toggle();
    });
    $(".clickable10").click(function(){
        $(".img100").toggle();
        $(".textclickable10").toggle();
    });
});